### PR TITLE
Update view_dl_cat_body.html

### PR DESCRIPTION
**Pull request by TazDevilBZH**
CSS class missing

### CODE REVIEW

**Comment by TazDevilBZH** [comment]
A CSS class is missing in order to get proper table alignment.

**Comment by oxpus** [comment]
THX for this hint.

**Comment by oxpus** [comment]
The package was updates to fix this error on footer stats.

I'll wait not for your language updates for the french package to update the extension itself to the next release.

**Comment by TazDevilBZH** [comment]
Files for translation uploaded on my GitHub, there are perhaps small issues left but it seems to work fine on my test board.

**Comment by oxpus** [comment]
THX for the language fixed.
The extension will not be released as 8.1.2.

**Comment by TazDevilBZH** [comment]
Thanks a lot for all the work you've done on this great extension. File manager is a big lack on phpBB and this extension is a good way to get rid of this lack.TazDevilBZH aliasFred BOURHIS
-------- Message d'origine --------De : Karsten Ude <notifications@github.com> Date : 08/08/2020  06:46  (GMT+01:00) À : oxpus/Download-32-Extension <Download-32-Extension@noreply.github.com> Cc : Fred BOURHIS <tazdevil56@free.fr>, Author <author@noreply.github.com> Objet : Re: [oxpus/Download-32-Extension] Update view_dl_cat_body.html (#16) 
THX for the language fixed.
The extension will not be released as 8.1.2.

**Pull request merged**
